### ISSUE TITLE
Try using Finda

### ISSUE THREAD

**Issue by ondrae** [openlexington/gethelpky#5]
Hi, I randomly saw this project on http://codeforamerica.org/brigade/projects

Looking at your mockups, you may want to use https://github.com/codeforboston/finda as a starting point. They've made it really easy to put points on a map with search.

It looks like you are building a wizard too, which makes it more complicated, but hopefully finda can help get you going. :rocket:

**Comment by eeeschwartz** [comment]
@ondrae thanks so much for the link, could be really good. 

If we go that route, we may find ourselves with a bridge between open referral data and finda. Interesting thought.

**Comment by eeeschwartz** [comment]
We definitely used and abused finda...

**Comment by ondrae** [comment]
:+1:
